
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookService", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookService {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "update", targetNamespace = "http://service/", className = "service.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://service/", className = "service.UpdateResponse")
    @Action(input = "http://service/BookService/updateRequest", output = "http://service/BookService/updateResponse")
    public void update(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        double arg3);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://service/", className = "service.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://service/", className = "service.DeleteResponse")
    @Action(input = "http://service/BookService/deleteRequest", output = "http://service/BookService/deleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "insertBook", targetNamespace = "http://service/", className = "service.InsertBook")
    @ResponseWrapper(localName = "insertBookResponse", targetNamespace = "http://service/", className = "service.InsertBookResponse")
    @Action(input = "http://service/BookService/insertBookRequest", output = "http://service/BookService/insertBookResponse")
    public void insertBook(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        double arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.Books>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "showBookByAuthor", targetNamespace = "http://service/", className = "service.ShowBookByAuthor")
    @ResponseWrapper(localName = "showBookByAuthorResponse", targetNamespace = "http://service/", className = "service.ShowBookByAuthorResponse")
    @Action(input = "http://service/BookService/showBookByAuthorRequest", output = "http://service/BookService/showBookByAuthorResponse")
    public List<Books> showBookByAuthor(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<service.Author>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "showAuthors", targetNamespace = "http://service/", className = "service.ShowAuthors")
    @ResponseWrapper(localName = "showAuthorsResponse", targetNamespace = "http://service/", className = "service.ShowAuthorsResponse")
    @Action(input = "http://service/BookService/showAuthorsRequest", output = "http://service/BookService/showAuthorsResponse")
    public List<Author> showAuthors();

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "insertAuthor", targetNamespace = "http://service/", className = "service.InsertAuthor")
    @ResponseWrapper(localName = "insertAuthorResponse", targetNamespace = "http://service/", className = "service.InsertAuthorResponse")
    @Action(input = "http://service/BookService/insertAuthorRequest", output = "http://service/BookService/insertAuthorResponse")
    public void insertAuthor(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "delBooksAndAuthors", targetNamespace = "http://service/", className = "service.DelBooksAndAuthors")
    @ResponseWrapper(localName = "delBooksAndAuthorsResponse", targetNamespace = "http://service/", className = "service.DelBooksAndAuthorsResponse")
    @Action(input = "http://service/BookService/delBooksAndAuthorsRequest", output = "http://service/BookService/delBooksAndAuthorsResponse")
    public void delBooksAndAuthors(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
